#!/bin/sh

set -x

HOSTNAME=`hostname`
REPO=backup@milhouse.podgorny.cz:attic/$HOSTNAME
ARCHIVE=`date +%Y%m%dT%H%M%S` 

attic init $REPO

attic create \
--verbose \
--do-not-cross-mountpoints --stats \
$REPO::$ARCHIVE \
/ /boot \
--exclude-caches \
--exclude /tmp \
--exclude /var/log/journal \
--exclude /var/cache/pacman/pkg \
--exclude /home/backup \
--exclude /home/*/tmp \
--exclude /home/*/.cache \
--exclude /home/*/.thumbnails

attic prune \
--stats \
--keep-within 7d \
--keep-daily 30 \
--keep-monthly 12 \
--keep-yearly 10 \
$REPO

