#!/bin/bash
set -e -x

HOST="admiral.podgorny.cz"
T="$1.asterix.cz"

if [ $1 == "mj04" ]; then T="10.140.8.52"; fi
if [ $1 == "mj18" ]; then T="10.140.23.52"; fi
if [ $1 == "mj22" ]; then T="10.140.42.52"; fi
if [ $1 == "mj36" ]; then T="10.140.47.52"; fi
if [ $1 == "mj48" ]; then T="10.140.44.52"; fi
if [ $1 == "mj101" ]; then T="10.140.38.52"; fi
if [ $1 == "mj107" ]; then T="10.140.73.52"; fi
if [ $1 == "mj125" ]; then T="10.140.34.52"; fi
if [ $1 == "mj126" ]; then T="10.140.74.52"; fi
if [ $1 == "mj143" ]; then T="10.140.66.52"; fi
if [ $1 == "mj148" ]; then T="10.140.36.52"; fi
if [ $1 == "mj151" ]; then T="10.140.62.52"; fi

ssh -N -L 5901:$T:5900 -L 3388:$T:3389 -L 2222:$T:22 $HOST
