#!/bin/sh
set -e -x

HOSTNAME=`hostname`
REMOTE=backup@milhouse.podgorny.cz
REPO=$REMOTE:borg/$HOSTNAME
ARCHIVE=`date +%Y%m%dT%H%M%S`

if [ "$1" = "--init" ]; then
	ssh-copy-id $REMOTE
	borg init $REPO
	exit
elif [ "$1" = "--break-lock" ]; then
	borg break-lock $REPO
	exit
fi

# TODO: isn't this handled by the --exclude below?
if [ -e /home/incoming ]; then
	INCOMING=/home/incoming
else
	INCOMING=""
fi

#--progress \
borg create \
--compression zlib,6 \
--one-file-system \
--stats \
$REPO::$ARCHIVE \
/ /boot ${INCOMING} \
--exclude-caches \
--exclude '/tmp/*' \
--exclude '/var/log/journal/*' \
--exclude '/var/cache/pacman/pkg/*' \
--exclude '/home/backup/*' \
--exclude '/home/incoming/*' \
--exclude '/home/*/mnt/*' \
--exclude '/home/*/tmp/*' \
--exclude '/home/*/.cache/*' \
--exclude '/home/*/.thumbnails/*' \
--exclude '/root/.cache/*'

borg prune \
--stats \
--keep-within 7d \
--keep-daily 30 \
--keep-monthly 12 \
--keep-yearly 10 \
$REPO

