#!/usr/bin/python3

import os
import subprocess
import socket
import tempfile
import sys


def main():
	remote_path = 'milhouse.podgorny.cz:bitcoin_shared'
	hostname = socket.gethostname()

	with tempfile.TemporaryDirectory() as local_path:
		subprocess.call('sshfs %s %s' % (remote_path, local_path), shell=True)

		if not os.listdir(local_path):
			raise Exception('%s empty after mount' % local_path)

		lock_fn = '%s/_lock' % local_path

		if os.path.isfile(lock_fn) and not '--force' in sys.argv:
			f = open(lock_fn, 'r')
			line = f.readline().strip()
			f.close()
			subprocess.call('fusermount -u %s' % local_path, shell=True)
			raise Exception('already locked by %s' % line)

		with open(lock_fn, 'w') as f:
			f.write(hostname)

		reindex = '-reindex' if '--reindex' in sys.argv else ''

		cmd = 'bitcoin-qt %s -datadir=%s' % (reindex, local_path)
		print(cmd)
		subprocess.call(cmd, shell=True)

		os.remove(lock_fn)

		subprocess.call('fusermount -u %s' % local_path, shell=True)


if __name__ == '__main__': main()
