#!/usr/bin/env bash

set -euo pipefail

      #--bind $HOME/.claude /claude \
      #--ro-bind $HOME/.local /claude/.local \
      #--setenv HOME /claude \
      #--setenv PATH /claude/bin:/claude/.local/bin:$PATH \

bwrap --ro-bind /usr /usr \
      --ro-bind /opt/claude-code /opt/claude-code \
      --bind $HOME/.claude $HOME/.claude \
      --bind $HOME/.claude.json $HOME/.claude.json \
      --dir /tmp \
      --dir /var \
      --symlink ../tmp var/tmp \
      --proc /proc \
      --dev /dev \
      --ro-bind /etc /etc \
      --ro-bind /run/systemd/resolve /run/systemd/resolve \
      --symlink usr/lib /lib \
      --symlink usr/lib64 /lib64 \
      --symlink usr/bin /bin \
      --symlink usr/sbin /sbin \
      --unshare-all \
      --share-net \
      --die-with-parent \
      --new-session \
      --dir /run/user/$(id -u) \
      --setenv XDG_RUNTIME_DIR "/run/user/`id -u`" \
      --setenv PS1 "bwrap " \
      --bind $(pwd) /work \
      --chdir /work \
      claude $@
