#!/usr/bin/env bash

set -euo pipefail

mkdir -p $HOME/opencode/home
echo "nameserver 9.9.9.9" > $HOME/opencode/resolv.conf

bwrap --ro-bind /usr /usr \
      --dir /tmp \
      --dir /var \
      --symlink ../tmp var/tmp \
      --proc /proc \
      --dev /dev \
      --symlink usr/lib /lib \
      --symlink usr/lib64 /lib64 \
      --symlink usr/bin /bin \
      --symlink usr/sbin /sbin \
      --unshare-all \
      --share-net \
      --die-with-parent \
      --new-session \
      --dir /run/user/$(id -u) \
      --setenv XDG_RUNTIME_DIR "/run/user/`id -u`" \
      --setenv PS1 "bwrap$ " \
      --ro-bind $HOME/opencode/resolv.conf /etc/resolv.conf \
      --ro-bind /etc/hosts /etc/hosts \
      --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
      --ro-bind /etc/passwd /etc/passwd \
      --ro-bind /etc/group /etc/group \
      --ro-bind /etc/localtime /etc/localtime \
      --ro-bind /etc/ssl /etc/ssl \
      --ro-bind-try /etc/ca-certificates /etc/ca-certificates \
      --bind $HOME/opencode/home $HOME \
      --ro-bind $HOME/opencode $HOME/opencode \
      --ro-bind $HOME/.local $HOME/host/.local \
      --setenv HOME $HOME \
      --setenv PATH $HOME/opencode/bin:$HOME/host/.local/bin:$PATH \
      --bind $(pwd) /work \
      --chdir /work \
      opencode $@
