#!/usr/bin/python3

def check_mkinitcpio():
	f = open('/etc/mkinitcpio.conf', 'r')

	for line in f:
		if line.startswith('HOOKS=') and 'autodetect' in line:
			return 'autodetect in hooks in mkinitcpio.conf'
		#endif
	#endfor

	f.close()
#enddef


def main():
	checks = [
		check_mkinitcpio,
	]

	for check in checks:
		err = check()
		if err: print(err)
	#endfor
#enddef


if __name__ == '__main__': main()
