#!/bin/sh
set -e -x
export GRAALVM_HOME=/usr/lib/jvm/java-11-graal
#exec clojure -Sdeps '{:deps {clj.native-image {:git/url "https://github.com/taylorwood/clj.native-image.git" :sha "0f113d46f9f0d07e8a29545c636431ddf5360a7d"}}}' -J-Dclojure.compiler.direct-linking=true -m clj.native-image "$@"
exec clojure -Sdeps '{:deps {clj.native-image {:git/url "https://github.com/taylorwood/clj.native-image.git" :sha "7708e7fd4572459c81f6a6b8e44c96f41cdd92d4"}}}' -J-Dclojure.compiler.direct-linking=true -m clj.native-image "$@"
