#!/usr/bin/python3

import sys
import subprocess
import time


# first item is default
TARGS = ['max', 'fix', 'min', 'mid']
PREFIX_POLICY = "/sys/devices/system/cpu/cpufreq/policy0"


def try_read(fn):
	try:
		with open(fn, 'r') as f:
			return f.read().strip()
	except:
		return None


def try_int(v):
	try:
		return int(v)
	except:
		return None


def toggle(fn):
	targ = try_read(fn)
	if not targ or targ not in TARGS:
		targ = TARGS[0]
	else:
		idx = TARGS.index(targ)
		targ = TARGS[(idx + 1) % len(TARGS)]
	with open(fn, 'w') as f:
		f.write(targ)
	return targ


def call(cmd):
	print('+ %s' % cmd)
	subprocess.call(cmd.split())


def main():
	fn = '/tmp/cpu_freq_crop'
	if len(sys.argv) >= 2 and sys.argv[1] == 'toggle':
		toggle(fn)
		return 0
	freq_min = try_int(try_read(f"{PREFIX_POLICY}/cpuinfo_min_freq"))
	freq_max = try_int(try_read(f"{PREFIX_POLICY}/cpuinfo_max_freq"))
	freq_base = try_int(try_read(f"{PREFIX_POLICY}/base_frequency"))
	print('freqs: %s %s %s' % (freq_min, freq_base, freq_max))
	freq_map = {
		'max': (freq_min, freq_max),
		'fix': (freq_base, freq_base),
		'min': (freq_min, freq_min),
		'mid': (freq_min, freq_base),
	}
	while 1:
		cur_gov = try_read(f"{PREFIX_POLICY}/scaling_governor")
		if cur_gov != "powersave":
			call('/usr/bin/sudo /usr/bin/cpupower frequency-set --governor powersave')
		cur_min = try_int(try_read(f"{PREFIX_POLICY}/scaling_min_freq"))
		cur_max = try_int(try_read(f"{PREFIX_POLICY}/scaling_max_freq"))
		targ = try_read(fn)
		if not targ:
			targ = toggle(fn)
		targ_min, targ_max = freq_map.get(targ)
		if cur_min != targ_min or cur_max != targ_max:
			call('/usr/bin/sudo /usr/bin/cpupower frequency-set --min %s --max %s' % (targ_min, targ_max))
		time.sleep(2)  # TODO: hard-coded shit
	return 0


if __name__ == '__main__':
	sys.exit(main())
