#!/bin/sh
set -e -x

PID=$1
SECS=30

sudo sh -c "echo 0 > /proc/sys/kernel/kptr_restrict"
sudo sh -c "echo 1 > /proc/sys/kernel/perf_event_paranoid"

exec clj -Sdeps '{:deps {com.clojure-goes-fast/clj-async-profiler {:mvn/version "0.1.3"}}}' -e "(require '[clj-async-profiler.core :as prof]) @(prof/profile-for ${PID} ${SECS} {}) (shutdown-agents)"
