#!/bin/sh
set -e -x
IMG="docker.io/ipfs/go-ipfs:v0.14.0"
#podman run --rm --net=host -v ipfs_data:/data/ipfs ${IMG} config Routing.Type dhtclient
#podman run --rm --net=host -v ipfs_data:/data/ipfs ${IMG} config Swarm.ConnMgr.HighWater 900
#podman run --rm --net=host -v ipfs_data:/data/ipfs ${IMG} config Swarm.ConnMgr.LowWater 600
podman run --rm --net=host -v ipfs_data:/data/ipfs ${IMG} config --json Swarm.ConnMgr.HighWater 50
podman run --rm --net=host -v ipfs_data:/data/ipfs ${IMG} config --json Swarm.ConnMgr.LowWater 10
exec podman run --rm --name=ipfs --net=host -v ipfs_data:/data/ipfs ${IMG} daemon --enable-pubsub-experiment --enable-namesys-pubsub --routing=dhtclient "$@"
