#!/usr/bin/python3

import subprocess
import glob
import os


def get_serial_number(dev):
	cmd = 'smartctl -i %s' % dev
	try:
		o = subprocess.check_output(cmd, shell=True).decode()
		for line in o.split('\n'):
			if 'Serial Number:' not in line:
				continue
			return line.split(':', 1)[1].strip()
	except Exception:
		pass
	return None


# this returns sectors, not bytes :-(
def get_size(dev):
	d = os.path.basename(dev)
	with open('/sys/block/%s/size' % d, 'r') as f:
		size = int(f.read().strip())
	return size


def get_devices():
	ret = glob.glob('/dev/sd?')
	ret.extend(glob.glob('/dev/nvme?n?'))
	return ret


def main():
	subprocess.call('lsblk -o NAME,SIZE,LABEL,MOUNTPOINTS,TRAN,ROTA,RM,HOTPLUG', shell=True)
	print()
	subprocess.call('btrfs fi show', shell=True)
	devs = sorted(get_devices())
	for dev in devs:
		sn = get_serial_number(dev)
		print('%s: %s' % (dev, sn))
	print()
	for dev in devs:
		sn = subprocess.call('mount | grep %s' % dev, shell=True)


if __name__ == '__main__':
	main()
