#!/bin/sh
set -e -x

test -x /usr/bin/makepkg
test -x /usr/bin/rsync
test -x /usr/bin/ssh

rm -f *.pkg.tar.zst

makepkg "$@"

scp ./*.pkg.tar.zst scp://arch@archlinux.podgorny.cz:2223/rpodgorny/
ssh -p 2223 arch@archlinux.podgorny.cz "./update rpodgorny"
