#!/usr/bin/python3

import os
import sys
import subprocess


def run(cmd):
	print('+ %s' % cmd)
	return subprocess.call(cmd, shell=True)


def main():
	vols = os.listdir('/mnt')
	vols = sorted(list(filter(lambda x: x.startswith('mfs_'), vols)))
	vols_opt = ''
	for vol in vols:
		vols_opt += ' -v /mnt/%s:/mnt/%s' % (vol, i)
	return run('docker run --rm -it --net=host %s --name mfschunkserver rpodgorny/moosefs ./mfschunkserver.sh' % vols_opt)


if __name__ == '__main__':
	sys.exit(main())
