#!/bin/sh
set -e -x
echo "NOTICE: this runs much faster when run under root"
#POOL=stratum+tcp://mine.moneropool.com:3333
POOL=stratum+tcp://pool.supportxmr.com:3333
exec /usr/bin/xmrig -o ${POOL} --donate-level=1 -u 48HdeM79tB3bMcGUrRH8NB1Hfh1sAYiep91zcpkUbyZwRhYNgaXbxb9Cqenn748H8cEnRNzCH1yjSN49vbSU4tr48AnNLcm -p x
