#!/bin/sh
set -e -x

DEV=$1
PI=$2  # 3 or 4

test -b ${DEV}

case "${PI}" in
	3|4) ;;
	*) echo "usage: $0 <device> <3|4>  (raspberry pi model)" >&2; exit 1 ;;
esac

if [ "$(cat /sys/block/$(basename ${DEV})/removable)" != "1" ]; then
	echo "${DEV} is not a removable device, refusing" >&2
	exit 1
fi

BOOT=${DEV}1
ROOT=${DEV}2
TMP=/var/tmp/archlivearm

#FN=ArchLinuxARM-rpi-latest.tar.gz
#FN=ArchLinuxARM-rpi-2-latest.tar.gz
FN=ArchLinuxARM-rpi-aarch64-latest.tar.gz
wget -c http://os.archlinuxarm.org/os/${FN} -O /var/tmp/${FN}

dd if=/dev/zero of=${DEV} bs=10M count=1
echo 'n
p
1

+1G
t
c
n
p
2


w
' | fdisk ${DEV}
partprobe
mkfs.vfat ${BOOT}
mkfs.ext4 -F ${ROOT}
rm -rf ${TMP}
mkdir -p ${TMP}/boot ${TMP}/root
mount ${BOOT} ${TMP}/boot
mount ${ROOT} ${TMP}/root
bsdtar -xpf /var/tmp/${FN} -C ${TMP}/root
mv ${TMP}/root/boot/* ${TMP}/boot
rm ${TMP}/root/etc/hostname
cp /home/radek/scripts/mkarcharm_init.sh ${TMP}/root/root/init.sh
if [ "${PI}" = "4" ]; then
	sed -i 's/mmcblk0/mmcblk1/g' ${TMP}/root/etc/fstab
fi
umount ${TMP}/boot ${TMP}/root
