#!/bin/sh
set -e -x

DEV=$1

test -b ${DEV}

BOOT=${DEV}1
ROOT=${DEV}2
TMP=/var/tmp/archlivearm

#FN=ArchLinuxARM-rpi-latest.tar.gz
#FN=ArchLinuxARM-rpi-2-latest.tar.gz
FN=ArchLinuxARM-rpi-aarch64-latest.tar.gz
wget -c http://os.archlinuxarm.org/os/${FN} -O /var/tmp/${FN}

dd if=/dev/zero of=${DEV} bs=10M count=1
echo 'n
p
1

+200M
t
c
n
p
2


w
' | fdisk ${DEV}
partprobe
mkfs.vfat ${BOOT}
mkfs.ext4 -F ${ROOT}
rm -rf ${TMP}
mkdir -p ${TMP}/boot ${TMP}/root
mount ${BOOT} ${TMP}/boot
mount ${ROOT} ${TMP}/root
bsdtar -xpf /var/tmp/${FN} -C ${TMP}/root
mv ${TMP}/root/boot/* ${TMP}/boot
rm ${TMP}/root/etc/hostname
cp /home/radek/scripts/mkarcharm_init.sh ${TMP}/root/root/init.sh
umount ${TMP}/boot ${TMP}/root
