#!/bin/sh
set -e -x

DEV=$1

test ${DEV}
test -b ${DEV}

#TMP=`mktemp -d`
MNT=banana_mnt

CWD=`pwd`
#cd ${TMP}

#rm -rf ArchLinuxARM-armv7-latest.tar.gz
test -f ArchLinuxARM-armv7-latest.tar.gz || wget -c http://archlinuxarm.org/os/ArchLinuxARM-armv7-latest.tar.gz

rm -rf u-boot
#git clone --depth=1 git://git.denx.de/u-boot.git
git clone https://github.com/rpodgorny/u-boot -b lamobo-r1 --depth=1

cd u-boot
#git checkout lamobo-r1
make CROSS_COMPILE=arm-linux-gnueabihf- Lamobo_R1_defconfig
make CROSS_COMPILE=arm-linux-gnueabihf-
cd ..

rm -rf boot.txt
wget https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/5b6a03409f982d566930b5cf078b55c9decf3a7c/alarm/uboot-sunxi/boot.txt
#rm -rf boot.txt

dd if=/dev/zero of=${DEV} bs=10M count=1
#parted --script -a optimal ${DEV} -- mklabel msdos mkpart primary fat32 0% 100MB mkpart primary ext2 100MB 100%
parted --script -a optimal ${DEV} -- mklabel msdos mkpart primary ext2 0% 100%
partprobe
#mkfs.vfat ${DEV}1
#mkfs.ext4 -F ${DEV}2
mkfs.ext4 -F ${DEV}1

umount -R ${MNT} || true
rmdir ${MNT} || true
mkdir -p ${MNT}
mount ${DEV}1 ${MNT}

bsdtar -xpf ArchLinuxARM-armv7-latest.tar.gz -C ${MNT}
#tar xvf ArchLinuxARM-armv7-latest.tar.gz -C ${MNT}

u-boot/tools/mkimage -A arm -O linux -T script -C none -n "U-Boot boot script" -d boot.txt ${MNT}/boot/boot.scr
cp u-boot/arch/arm/dts/sun7i-a20-lamobo-r1.dtb ${MNT}/boot/dtbs/

sync
umount -R ${MNT}
rmdir ${MNT}

dd if=u-boot/u-boot-sunxi-with-spl.bin of=${DEV} bs=1024 seek=8

cd ${CWD}
#rm -rf ${TMP}
