#!/usr/bin/python3

'''
mmm.

Usage:
  mmm [options]

Options:
  --random     Randomize order.
  --no-repeat  Don't play forever.
'''

__version__ = '0.0'

import os
import subprocess
import time
import random
import docopt
import platform


def main():
	args = docopt.docopt(__doc__, version=__version__)
	fns = sorted(os.listdir('.'))
	if args['--random']:
		random.shuffle(fns)
	while 1:
		for fn in fns:
			if 'arm' in platform.machine():
				if fn.lower().endswith('.mp3'):
					#cmd = 'mplayer "./%s"' % fn
					cmd = 'omxplayer -o hdmi "./%s"' % fn
				else:
					cmd = 'omxplayer -b -o hdmi "./%s"' % fn
			else:
				cmd = 'mplayer "./%s"' % fn
			print('>>> %s' % cmd)
			subprocess.call(cmd, shell=True)
		if args['--no-repeat']:
			break
		time.sleep(1)


if __name__ == '__main__':
	main()
