#!/usr/bin/python3

import os
import subprocess
import time


def main():
	while 1:
		for fn in sorted(os.listdir('.')):
			cmd = 'omxplayer -b -o hdmi "./%s"' % fn
			print('>>> %s' % cmd)
			subprocess.call(cmd, shell=True)
		#endfor

		time.sleep(1)
	#endwhile
#enddef


if __name__ == '__main__':
	main()
#endif
