#!/bin/bash

repo="rpodgorny"

# get all packages installed from your repo
pkgs=$(pacman -Sl $repo | awk '/installed:/{print $2}')

for pkg in $pkgs; do
    local_ver=$(pacman -Q $pkg | awk '{print $2}')
    aur_ver=$(curl -s "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$pkg" \
        | jq -r '.results[0].Version')

    if [ "$aur_ver" != "null" ] && [ "$local_ver" != "$aur_ver" ]; then
        echo "$pkg $local_ver -> $aur_ver"
    fi
done
