#!/usr/bin/python3

import subprocess
import sys


def main():
    th = sys.argv[1] if len(sys.argv) > 1 else None
    if th is None:
        p = subprocess.run("gsettings get org.gnome.desktop.interface gtk-theme | grep Inverse", shell=True, stdout=subprocess.DEVNULL)  # a stupid and simple way to get currently set theme
        th = "light" if p.returncode == 0 else "dark"  # do the inversion
    print(f"new theme: {th}")
    assert th in {"light", "dark"}

    # for some reason, we have to set both "global" theme and "gtk" theme
    val = "prefer-light" if th == "light" else "prefer-dark"
    subprocess.run(f"gsettings set org.gnome.desktop.interface color-scheme {val}", shell=True)
    val = "HighContrast" if th == "light" else "HighContrastInverse"
    subprocess.run(f"gsettings set org.gnome.desktop.interface gtk-theme {val}", shell=True)

    val = "foot-selenized-white" if th == "light" else "foot-selenized-black"
    subprocess.run(f"ln -sf {val} foot-theme", shell=True, cwd="/home/radek/dotfiles")

    val = "style-light.css" if th == "light" else "style-dark.css"
    subprocess.run(f"ln -sf {val} style.css", shell=True, cwd="/home/radek/.config/waybar")
    subprocess.run("pkill -SIGUSR2 waybar", shell=True)

    subprocess.run("swaymsg reload", shell=True)


if __name__ == "__main__":
    sys.exit(main())
