#!/bin/sh
set -e -x

DEV="hpaio:/usb/Photosmart_B010_series?serial=CN08L2K1Y105K9"
RES=600
fn=scan_$(date +"%Y%m%d_%H%M%S")

#scanimage -d epson2 --mode Color --resolution $RES --progress >/tmp/${fn}.pnm \
#scanimage --mode Color --resolution $RES --progress \
#| grep -v 'Failed cupsGetDevices' >/tmp/${fn}.pnm \
#&& convert /tmp/${fn}.pnm ${fn}.jpg \
#&& rm /tmp/${fn}.pnm

scanimage --mode Color -d "$DEV" --resolution $RES --progress --format jpeg >${fn}.jpg_
mv ${fn}.jpg_ ${fn}.jpg

identify ${fn}.jpg
