#!/bin/sh
set -e -x

RES=600
fn=scan_$(date +"%Y%m%d_%H%M%S")

#scanimage -d epson2 --mode Color --resolution $RES --progress >/tmp/${fn}.pnm \
#scanimage --mode Color --resolution $RES --progress \
#| grep -v 'Failed cupsGetDevices' >/tmp/${fn}.pnm \
#&& convert /tmp/${fn}.pnm ${fn}.jpg \
#&& rm /tmp/${fn}.pnm

scanimage --mode Color --resolution $RES --format jpeg --progress >${fn}.jpg

identify ${fn}.jpg
