#!/bin/sh
podman run --rm --net=host docker.io/chrislusf/seaweedfs:3.71_large_disk filer -ip.bind=[::] -ip=ruprt.podgorny.cz -master=ruprt.podgorny.cz:9333,orion.asterix.cz:9333,muflon.asterix.cz:9333
