#!/bin/sh
set -e -x

IP=`ip addr|grep "inet6 2"|choose 1|choose -f "/" 0`

IMG="docker.io/chrislusf/seaweedfs:3.71_large_disk"

podman run --rm --net=host ${IMG} filer -ip.bind=[::] -master=ruprt.podgorny.cz:9333,orion.asterix.cz:9333,muflon.asterix.cz:9333 -ip=${IP}
