#!/bin/sh
podman run --rm --net=host --name=swvolume docker.io/chrislusf/seaweedfs:3.71_large_disk volume --index=leveldb -ip.bind=[::] -mserver=ruprt.podgorny.cz:9333,orion.asterix.cz:9333,muflon.asterix.cz:9333 -ip=ruprt.podgorny.cz
