#!/bin/sh
podman run --rm --net=host --name=swmaster docker.io/chrislusf/seaweedfs:3.71_large_disk master -defaultReplication=001 -ip.bind=[::] -ip=ruprt.podgorny.cz -peers=ruprt.podgorny.cz:9333,orion.asterix.cz:9333,muflon.asterix.cz:9333
