#!/bin/sh
set -e -x

IP=`ip addr|grep "inet6 2"|choose 1|choose -f "/" 0`

IMG="docker.io/chrislusf/seaweedfs:3.73_large_disk"

podman run --rm --net=host --name=swvolume ${IMG} volume -index=leveldb -minFreeSpace=10GiB -ip.bind=[::] -mserver=ruprt.podgorny.cz:9333,orion.asterix.cz:9333,muflon.asterix.cz:9333 -ip=${IP}
