#!/bin/sh
set -e -x

CON=`nmcli -t -f GENERAL.CONNECTION --mode tabular device show $DEVICE | head -n1`
exec nmcli connection modify "$CON" connection.metered yes

#DEV=wlp2s0
#exec nmcli dev modify $DEV connection.METERED yes
#exec nmcli dev modify $DEV connection.METERED unknown
