#!/usr/bin/python3

'''
SureBoot.

Usage:
  sureboot [update]
  sureboot new <device>

Arguments:
  <device>  Target device.

Options:
  -h, --help  This screen.
'''

import os
import os.path
import subprocess
import docopt
import glob


def call(cmd):
	print('$ %s' % cmd)
	os.system(cmd)
#enddef


def update():
	with open('/etc/fstab', 'r') as f:
		for line in f:
			if '/boot' in line and not line.startswith('#'):
				raise Exception('/boot partition is in fstab')
			#endif
		#endfor
	#endwith

	if not os.path.isfile('/etc/systemd/system/boot.mount'):
		print('/etc/systemd/system/boot.mount does not exist')
		return
	#endif

	# TODO: actually verify where does the link point to
	if not os.path.islink('/etc/systemd/system/local-fs.target.wants/boot.mount'):
		raise Exception('/etc/systemd/system/local-fs.target.wants/boot.mount link does not exist')
	#endif

	# TODO: this may be simpler but does not check the fs type
	#if not os.path.ismount('/boot'):

	boot_part = None
	with open('/proc/self/mounts', 'r') as f:
		for line in f:
			if '/boot' in line and 'vfat' in line:
				boot_part = line.split()[0]
				break
			#endif
		else:
			raise Exception('/boot partition not mounted')
		#endfor
	#endwith

	boot_parts = subprocess.check_output('blkid -o device -t LABEL=BOOT', shell=True).decode().strip().split('\n')

	if not boot_parts:
		raise Exception('no backup BOOT partitions!')
	#endif

	mbr_devs = []
	for dev in os.listdir('/sys/class/block'):
		if not dev.startswith('sd'): continue
		if not os.path.isfile('/sys/class/block/%s/removable' % dev): continue
		if not open('/sys/class/block/%s/removable' % dev).read() != '0': continue
		mbr_devs.append(dev)
	#endfor

	if not mbr_devs:
		raise Exception('no devices to install mbr to')
	#endif

	call('mkdir /tmp/sureboot')

	for part in boot_parts:
		if part == boot_part: continue

		call('mount %s /tmp/sureboot' % part)
		call('rm -rf /tmp/sureboot/*')
		call('cp -av /boot/* /tmp/sureboot/')
		call('extlinux --install -r /tmp/sureboot')
		call('umount /tmp/sureboot')
	#endfor

	call('rmdir /tmp/sureboot')

	for dev in mbr_devs:
		call('dd if=/usr/lib/syslinux/bios/mbr.bin of=/dev/%s bs=440 count=1 conv=notrunc' % dev)
	#endfor

	call('sync')
#enddef


def new(dev):
	if glob.glob('%s?' % dev):
		raise Exception('%s does not seem to be empty drive' % dev)
	#endif

	cmd = '''echo "n
p
1

+100M
n
p
2

+1000M
n
p
3


t
1
0c
t
2
82
a
1
w
q
" | fdisk %s''' % dev
	call(cmd)

	call('mkfs.vfat -n BOOT %s1' % dev)
	call('mkswap -L SWAP %s2' % dev)
	call('btrfs device add %s3 /' % dev)
#enddef


def main():
	args = docopt.docopt(__doc__)

	if args['new']:
		new(args['<device>'])
		update()
	elif args['update']:
		update()
	else:
		print('no command specified, inferring update')
		update()
	#endif
#enddef


if __name__ == '__main__': main()
