#!/usr/bin/python3

'''
SureBoot.

Usage:
  sureboot [update]
  sureboot add <device>
  sureboot remove <device>

Arguments:
  <device>  Target device.

Options:
  -h, --help  This screen.
'''

import os
import os.path
import subprocess
import docopt
import glob


def call(cmd):
	print('$ %s' % cmd)
	os.system(cmd)
#enddef


def update():
	with open('/etc/fstab', 'r') as f:
		for line in f:
			if '/boot' in line and not line.startswith('#'):
				break
			#endif
		else:
			raise Exception('/boot partition not in fstab')
		#endfor
	#endwith

	#if not os.path.isfile('/etc/systemd/system/boot.mount'):
	#	print('/etc/systemd/system/boot.mount does not exist')
	#	return
	#endif

	# TODO: actually verify where does the link point to
	#if not os.path.islink('/etc/systemd/system/local-fs.target.wants/boot.mount'):
	#	raise Exception('/etc/systemd/system/local-fs.target.wants/boot.mount link does not exist')
	#endif

	# TODO: this may be simpler but does not check the fs type
	#if not os.path.ismount('/boot'):

	boot_part = None
	with open('/proc/self/mounts', 'r') as f:
		for line in f:
			if '/boot' in line and 'vfat' in line:
				boot_part = line.split()[0]
				break
			#endif
		else:
			raise Exception('/boot partition not mounted')
		#endfor
	#endwith

	boot_parts = subprocess.check_output('blkid -o device -t LABEL=BOOT', shell=True).decode().strip().split('\n')

	if not boot_parts:
		raise Exception('no backup BOOT partitions!')
	#endif

	mbr_devs = []
	for dev in os.listdir('/sys/class/block'):
		if not dev.startswith('sd'): continue
		if not os.path.isfile('/sys/class/block/%s/removable' % dev): continue
		if not open('/sys/class/block/%s/removable' % dev).read() != '0': continue
		mbr_devs.append(dev)
	#endfor

	if not mbr_devs:
		raise Exception('no devices to install mbr to')
	#endif

	call('umount %s' % boot_part)
	call('fsck.vfat -a %s' % boot_part)
	call('mount %s /boot' % boot_part)

	call('mkdir /tmp/sureboot')

	for part in boot_parts:
		if part == boot_part: continue

		call('fsck.vfat -a %s' % part)
		call('mount %s /tmp/sureboot' % part)
		call('rm -rf /tmp/sureboot/*')
		call('cp -av /boot/* /tmp/sureboot/')
		call('extlinux --install -r /tmp/sureboot')
		call('umount /tmp/sureboot')
	#endfor

	call('rmdir /tmp/sureboot')

	for dev in mbr_devs:
		call('dd if=/usr/lib/syslinux/bios/mbr.bin of=/dev/%s bs=440 count=1 conv=notrunc' % dev)
	#endfor

	call('sync')
#enddef


def add(dev):
	if glob.glob('%s?' % dev):
		raise Exception('%s does not seem to be empty drive' % dev)
	#endif

	cmd = '''echo "n
p
1

+100M
n
p
2

+1000M
n
p
3


t
1
0c
t
2
82
a
1
w
q
" | fdisk %s''' % dev
	call(cmd)

	assert set(glob.glob('%s?' % dev)) == set('%s%d' % (dev, i) for i in range(1, 4))

	call('mkfs.vfat -n BOOT %s1' % dev)
	call('mkswap -L SWAP %s2' % dev)
	call('btrfs device add %s3 /' % dev)
	call('swapon %s2' % dev)
#enddef


def remove(dev):
	assert set(glob.glob('%s?' % dev)) == set('%s%d' % (dev, i) for i in range(1, 4))

	# /boot can be mounted from the removed drive so unmount it just to be sure
	call('umount /boot')
	call('systemctl stop boot.mount')

	call('btrfs device delete %s3 /' % dev)
	call('wipefs %s3' % dev)
	call('swapoff %s2' % dev)
	call('wipefs %s1' % dev)

	call('dd if=/dev/zero of=%s bs=512 count=1' % dev)

	call('mount /boot')
	call('systemctl start boot.mount')
#enddef


def main():
	args = docopt.docopt(__doc__)

	if args['add']:
		add(args['<device>'])
		update()
	elif args['remove']:
		remove(args['<device>'])
	elif args['update']:
		update()
	else:
		print('no command specified, doing update')
		update()
	#endif
#enddef


if __name__ == '__main__': main()
