#!/bin/sh
set -e -x

rm -rf .venv

uv venv "$@"

if [ -f requirements.txt ]; then
  uv pip install -r requirements.txt
fi
if [ -f requirements-dev.txt ]; then
  uv pip install -r requirements-dev.txt
fi
