#!/bin/sh
set -e -x

HOST=$1
FN=$2
PWD=$3
test ! -z "$HOST"
test ! -z "$FN"
test ! -z "$PWD"

exec vncsnapshot -password $PWD -quality 80 $HOST $FN
exit 0

socat tcp-listen:5900,reuseaddr,fork tcp-connect:$HOST:5900 &
sleep 3
vncsnapshot -password $PWD -quality 80 127.0.0.1:0 $FN
killall socat
