#!/bin/sh
export VSCODE_GALLERY_SERVICE_URL="https://marketplace.visualstudio.com/_apis/public/gallery"
export VSCODE_GALLERY_CACHE_URL="https://vscode.blob.core.windows.net/gallery/index"
export VSCODE_GALLERY_ITEM_URL="https://marketplace.visualstudio.com/items"
exec vscodium --enable-features=UseOzonePlatform --ozone-platform=wayland "$@"
